### ISSUE TITLE
Tracking issue: Better coverage of C functions

### ISSUE THREAD

**Issue by Erk-** [Erk-/genfut#33]
This is a tracking issue for offering better support for the Futhark C-API

### Configuration
- [ ] [`futhark_context_config_set_debugging`](https://futhark.readthedocs.io/en/stable/c-api.html#c.futhark_context_config_set_debugging)
- [ ] [`futhark_context_config_set_profiling`](https://futhark.readthedocs.io/en/stable/c-api.html#c.futhark_context_config_set_profiling)
- [ ] [`futhark_context_config_set_logging`](https://futhark.readthedocs.io/en/stable/c-api.html#c.futhark_context_config_set_logging)
- [ ] [`futhark_context_config_set_tuning_param`](https://futhark.readthedocs.io/en/stable/c-api.html#c.futhark_context_config_set_tuning_param)
- [ ] [`futhark_get_tuning_param_count`](https://futhark.readthedocs.io/en/stable/c-api.html#c.futhark_get_tuning_param_count)
- [ ] [`futhark_get_tuning_param_name`](https://futhark.readthedocs.io/en/stable/c-api.html#c.futhark_get_tuning_param_name)
- [ ] [`futhark_get_tuning_param_name`](https://futhark.readthedocs.io/en/stable/c-api.html#c.futhark_get_tuning_param_name)
- [ ] [`futhark_get_tuning_param_class`](https://futhark.readthedocs.io/en/stable/c-api.html#c.futhark_get_tuning_param_class)
- [ ] [`futhark_context_config_set_cache_file`](https://futhark.readthedocs.io/en/stable/c-api.html#c.futhark_context_config_set_cache_file)

### Context

- [ ] [`futhark_context_pause_profiling`](https://futhark.readthedocs.io/en/stable/c-api.html#c.futhark_context_pause_profiling)
- [ ] [`futhark_context_unpause_profiling`](https://futhark.readthedocs.io/en/stable/c-api.html#c.futhark_context_unpause_profiling)
- [ ] [`futhark_context_get_error`](https://futhark.readthedocs.io/en/stable/c-api.html#c.futhark_context_get_error)
- [ ] [`futhark_context_set_logging_file`](https://futhark.readthedocs.io/en/stable/c-api.html#c.futhark_context_set_logging_file)
- [ ] [`futhark_context_report`](https://futhark.readthedocs.io/en/stable/c-api.html#c.futhark_context_report)
- [ ] [`futhark_context_clear_caches`](https://futhark.readthedocs.io/en/stable/c-api.html#c.futhark_context_clear_caches)

### Opaque values

- [ ] [`futhark_store_opaque_foo`](https://futhark.readthedocs.io/en/stable/c-api.html#c.futhark_store_opaque_foo)
- [ ] [`futhark_restore_opaque_foo`](https://futhark.readthedocs.io/en/stable/c-api.html#c.futhark_restore_opaque_foo)

### GPU

- [ ] [`futhark_context_config_set_device`](https://futhark.readthedocs.io/en/stable/c-api.html#c.futhark_context_config_set_device)

### OpenCL

- [ ] [`futhark_context_config_set_platform`](https://futhark.readthedocs.io/en/stable/c-api.html#c.futhark_context_config_set_platform)
- [ ] [`futhark_context_config_select_device_interactively`](https://futhark.readthedocs.io/en/stable/c-api.html#c.futhark_context_config_select_device_interactively)
- [ ] [`futhark_context_new_with_command_queue`](https://futhark.readthedocs.io/en/stable/c-api.html#c.futhark_context_new_with_command_queue)
- [ ] [`futhark_context_get_command_queue`](https://futhark.readthedocs.io/en/stable/c-api.html#c.futhark_context_get_command_queue)

### Exotic

- [ ] [`futhark_context_config_set_default_group_size`](https://futhark.readthedocs.io/en/stable/c-api.html#c.futhark_context_config_set_default_group_size)
- [ ] [`futhark_context_config_set_default_num_groups`](https://futhark.readthedocs.io/en/stable/c-api.html#c.futhark_context_config_set_default_num_groups)
- [ ] [`futhark_context_config_set_default_tile_size`](https://futhark.readthedocs.io/en/stable/c-api.html#c.futhark_context_config_set_default_tile_size)
- [ ] [`futhark_context_config_dump_program_to`](https://futhark.readthedocs.io/en/stable/c-api.html#c.futhark_context_config_dump_program_to)
- [ ] [`futhark_context_config_load_program_from`](https://futhark.readthedocs.io/en/stable/c-api.html#c.futhark_context_config_load_program_from)

### Multicore

- [ ] [`context_config_set_num_threads`](https://futhark.readthedocs.io/en/stable/c-api.html#c.context_config_set_num_threads)
